"""Initial schema

Revision ID: 627716ebfd69
Revises:
Create Date: 2025-11-20 07:56:52.106890+00:00

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "627716ebfd69"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_sessions",
        sa.Column("session_token", sa.String(length=128), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("identifier_type", sa.String(length=10), nullable=False),
        sa.Column("otp_code", sa.String(length=6), nullable=True),
        sa.Column("otp_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_activity_at", sa.DateTime(timezone=True), server_default="NOW()", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("expires_at > created_at", name="valid_expiry"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_sessions_created_at"), "customer_sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_customer_sessions_expires_at"), "customer_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_customer_sessions_identifier"), "customer_sessions", ["identifier"], unique=False
    )
    op.create_index(
        op.f("ix_customer_sessions_is_verified"), "customer_sessions", ["is_verified"], unique=False
    )
    op.create_index(
        op.f("ix_customer_sessions_session_token"),
        "customer_sessions",
        ["session_token"],
        unique=True,
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("business_license_number", sa.String(length=100), nullable=False),
        sa.Column("tax_id", sa.String(length=50), nullable=False),
        sa.Column("address_line1", sa.String(length=255), nullable=False),
        sa.Column("address_line2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("zip_code", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_review", "approved", "suspended", "rejected", name="organizationstatus"
            ),
            nullable=False,
        ),
        sa.Column("stripe_account_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("business_license_number"),
        sa.UniqueConstraint("business_license_number", name="uq_business_license"),
        sa.UniqueConstraint("email", name="uq_organization_email"),
        sa.UniqueConstraint("stripe_account_id"),
    )
    op.create_index(
        op.f("ix_organizations_created_at"), "organizations", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_organizations_email"), "organizations", ["email"], unique=True)
    op.create_index(op.f("ix_organizations_name"), "organizations", ["name"], unique=False)
    op.create_index(op.f("ix_organizations_status"), "organizations", ["status"], unique=False)
    op.create_table(
        "drivers",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("drivers_license_number", sa.String(length=50), nullable=False),
        sa.Column("drivers_license_state", sa.String(length=2), nullable=False),
        sa.Column("drivers_license_expiry", sa.String(length=10), nullable=False),
        sa.Column("has_cdl", sa.Boolean(), nullable=False),
        sa.Column("cdl_class", sa.String(length=10), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("background_check_completed", sa.Boolean(), nullable=False),
        sa.Column("photo_url", sa.String(length=512), nullable=True),
        sa.Column("license_front_url", sa.String(length=512), nullable=True),
        sa.Column("license_back_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(has_cdl = false) OR (has_cdl = true AND cdl_class IS NOT NULL)",
            name="cdl_requires_class",
        ),
        sa.CheckConstraint("LENGTH(drivers_license_state) = 2", name="valid_state_code"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drivers_created_at"), "drivers", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_drivers_drivers_license_number"),
        "drivers",
        ["drivers_license_number"],
        unique=True,
    )
    op.create_index(op.f("ix_drivers_email"), "drivers", ["email"], unique=True)
    op.create_index(op.f("ix_drivers_is_verified"), "drivers", ["is_verified"], unique=False)
    op.create_index(op.f("ix_drivers_org_id"), "drivers", ["org_id"], unique=False)
    op.create_table(
        "insurance_policies",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "policy_type",
            sa.Enum("liability", "cargo", "workers_comp", "auto", name="insurancetype"),
            nullable=False,
        ),
        sa.Column("policy_number", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("coverage_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("document_url", sa.String(length=512), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("coverage_amount > 0", name="positive_coverage"),
        sa.CheckConstraint("expiry_date > effective_date", name="valid_date_range"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "policy_type", name="uq_org_policy_type"),
        sa.UniqueConstraint("policy_number"),
    )
    op.create_index(
        op.f("ix_insurance_policies_created_at"), "insurance_policies", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_insurance_policies_expiry_date"),
        "insurance_policies",
        ["expiry_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_insurance_policies_org_id"), "insurance_policies", ["org_id"], unique=False
    )
    op.create_table(
        "pricing_configs",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("base_hourly_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("base_mileage_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("minimum_charge", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("surcharge_rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("base_hourly_rate > 0", name="positive_hourly_rate"),
        sa.CheckConstraint("base_mileage_rate >= 0", name="non_negative_mileage_rate"),
        sa.CheckConstraint("minimum_charge >= 0", name="non_negative_minimum"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pricing_configs_created_at"), "pricing_configs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_configs_is_active"), "pricing_configs", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_pricing_configs_org_id"), "pricing_configs", ["org_id"], unique=False)
    op.create_table(
        "trucks",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("license_plate", sa.String(length=20), nullable=False),
        sa.Column("make", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "size", sa.Enum("SMALL", "MEDIUM", "LARGE", "XLARGE", name="trucksize"), nullable=False
        ),
        sa.Column("capacity_cubic_feet", sa.Integer(), nullable=False),
        sa.Column("max_weight_lbs", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "IN_USE", "MAINTENANCE", "INACTIVE", name="truckstatus"),
            nullable=False,
        ),
        sa.Column(
            "base_location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("registration_number", sa.String(length=50), nullable=False),
        sa.Column("registration_expiry", sa.String(length=10), nullable=False),
        sa.Column("insurance_document_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("capacity_cubic_feet > 0", name="positive_capacity"),
        sa.CheckConstraint("max_weight_lbs > 0", name="positive_weight"),
        sa.CheckConstraint("year >= 1990 AND year <= 2030", name="valid_year"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registration_number"),
    )
    op.create_index(op.f("ix_trucks_created_at"), "trucks", ["created_at"], unique=False)
    op.create_index(op.f("ix_trucks_license_plate"), "trucks", ["license_plate"], unique=True)
    op.create_index(op.f("ix_trucks_org_id"), "trucks", ["org_id"], unique=False)
    op.create_index(op.f("ix_trucks_status"), "trucks", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "org_owner", "org_manager", "org_staff", name="userrole"),
            nullable=False,
        ),
        sa.Column("has_2fa_enabled", sa.Boolean(), nullable=False),
        sa.Column("totp_secret", sa.String(length=32), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_user_email"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("truck_id", sa.UUID(), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("customer_email", sa.String(length=255), nullable=False),
        sa.Column("customer_phone", sa.String(length=20), nullable=False),
        sa.Column("move_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pickup_address", sa.String(length=512), nullable=False),
        sa.Column("pickup_city", sa.String(length=100), nullable=False),
        sa.Column("pickup_state", sa.String(length=50), nullable=False),
        sa.Column("pickup_zip", sa.String(length=10), nullable=False),
        sa.Column("dropoff_address", sa.String(length=512), nullable=False),
        sa.Column("dropoff_city", sa.String(length=100), nullable=False),
        sa.Column("dropoff_state", sa.String(length=50), nullable=False),
        sa.Column("dropoff_zip", sa.String(length=10), nullable=False),
        sa.Column("estimated_distance_miles", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("estimated_duration_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("commute_buffer_minutes", sa.Integer(), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("special_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pickup_floors", sa.Integer(), nullable=False),
        sa.Column("dropoff_floors", sa.Integer(), nullable=False),
        sa.Column("has_elevator_pickup", sa.Boolean(), nullable=False),
        sa.Column("has_elevator_dropoff", sa.Boolean(), nullable=False),
        sa.Column("estimated_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("final_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("platform_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "in_progress",
                "completed",
                "cancelled",
                name="bookingstatus",
            ),
            nullable=False,
        ),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.text("truck_id"), "="),
            (sa.text("tstzrange(effective_start, effective_end)"), "&&"),
            using="gist",
            name="exclude_overlapping_bookings",
        ),
        sa.CheckConstraint("commute_buffer_minutes >= 0", name="non_negative_buffer"),
        sa.CheckConstraint("dropoff_floors >= 0", name="non_negative_dropoff_floors"),
        sa.CheckConstraint("effective_end > effective_start", name="valid_time_window"),
        sa.CheckConstraint("estimated_amount >= 0", name="non_negative_amount"),
        sa.CheckConstraint("estimated_distance_miles > 0", name="positive_distance"),
        sa.CheckConstraint("estimated_duration_hours > 0", name="positive_duration"),
        sa.CheckConstraint("pickup_floors >= 0", name="non_negative_pickup_floors"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["truck_id"], ["trucks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_payment_intent_id"),
    )
    op.create_index(
        "idx_booking_availability",
        "bookings",
        ["truck_id", "effective_start", "effective_end"],
        unique=False,
    )
    op.create_index(op.f("ix_bookings_created_at"), "bookings", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_bookings_customer_email"), "bookings", ["customer_email"], unique=False
    )
    op.create_index(op.f("ix_bookings_effective_end"), "bookings", ["effective_end"], unique=False)
    op.create_index(
        op.f("ix_bookings_effective_start"), "bookings", ["effective_start"], unique=False
    )
    op.create_index(op.f("ix_bookings_move_date"), "bookings", ["move_date"], unique=False)
    op.create_index(op.f("ix_bookings_org_id"), "bookings", ["org_id"], unique=False)
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(op.f("ix_bookings_truck_id"), "bookings", ["truck_id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("platform_fee", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ISSUED", "PAID", "OVERDUE", "CANCELLED", name="invoicestatus"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("stripe_invoice_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("pdf_url", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("platform_fee >= 0", name="non_negative_platform_fee"),
        sa.CheckConstraint("subtotal >= 0", name="non_negative_subtotal"),
        sa.CheckConstraint("tax_amount >= 0", name="non_negative_tax"),
        sa.CheckConstraint("total_amount = subtotal + tax_amount", name="valid_total_calculation"),
        sa.CheckConstraint("total_amount >= 0", name="non_negative_total"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("booking_id", name="uq_invoice_booking"),
        sa.UniqueConstraint("stripe_invoice_id"),
    )
    op.create_index(op.f("ix_invoices_booking_id"), "invoices", ["booking_id"], unique=True)
    op.create_index(op.f("ix_invoices_created_at"), "invoices", ["created_at"], unique=False)
    op.create_index(op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=True)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "county_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("st_code", "co_code", name=op.f("county_lookup_pkey")),
    )
    op.create_index(op.f("county_lookup_state_idx"), "county_lookup", ["state"], unique=False)
    op.create_index(
        op.f("county_lookup_name_idx"),
        "county_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
    )
    op.create_table(
        "place_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("pl_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("st_code", "pl_code", name=op.f("place_lookup_pkey")),
        schema="tiger",
    )
    op.create_index(
        op.f("place_lookup_state_idx"), "place_lookup", ["state"], unique=False, schema="tiger"
    )
    op.create_index(
        op.f("place_lookup_name_idx"),
        "place_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
        schema="tiger",
    )
    op.create_table(
        "secondary_unit_lookup",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("abbrev", sa.VARCHAR(length=5), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("secondary_unit_lookup_pkey")),
    )
    op.create_index(
        op.f("secondary_unit_lookup_abbrev_idx"), "secondary_unit_lookup", ["abbrev"], unique=False
    )
    op.create_table(
        "tabblock",
        sa.Column("gid", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("statefp", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("countyfp", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
        sa.Column("tractce", sa.VARCHAR(length=6), autoincrement=False, nullable=True),
        sa.Column("blockce", sa.VARCHAR(length=4), autoincrement=False, nullable=True),
        sa.Column("tabblock_id", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("mtfcc", sa.VARCHAR(length=5), autoincrement=False, nullable=True),
        sa.Column("ur", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("uace", sa.VARCHAR(length=5), autoincrement=False, nullable=True),
        sa.Column("funcstat", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("aland", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("awater", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("intptlat", sa.VARCHAR(length=11), autoincrement=False, nullable=True),
        sa.Column("intptlon", sa.VARCHAR(length=12), autoincrement=False, nullable=True),
        sa.Column(
            "the_geom",
            geoalchemy2.types.Geometry(
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL",
            name=op.f("enforce_geotype_geom"),
        ),
        sa.CheckConstraint("st_ndims(the_geom) = 2", name=op.f("enforce_dims_geom")),
        sa.CheckConstraint("st_srid(the_geom) = 4269", name=op.f("enforce_srid_geom")),
        sa.PrimaryKeyConstraint("tabblock_id", name=op.f("tabblock_pkey")),
    )
    op.create_table(
        "countysub_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("county", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cs_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "st_code", "co_code", "cs_code", name=op.f("countysub_lookup_pkey")
        ),
    )
    op.create_index(op.f("countysub_lookup_state_idx"), "countysub_lookup", ["state"], unique=False)
    op.create_index(
        op.f("countysub_lookup_name_idx"),
        "countysub_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
    )
    op.create_table(
        "place_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("pl_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("st_code", "pl_code", name=op.f("place_lookup_pkey")),
    )
    op.create_index(op.f("place_lookup_state_idx"), "place_lookup", ["state"], unique=False)
    op.create_index(
        op.f("place_lookup_name_idx"),
        "place_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
    )
    op.create_table(
        "zip_lookup",
        sa.Column("zip", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("county", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cs_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cousub", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("pl_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("place", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cnt", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("zip", name=op.f("zip_lookup_pkey")),
    )
    op.create_table(
        "secondary_unit_lookup",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("abbrev", sa.VARCHAR(length=5), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("secondary_unit_lookup_pkey")),
        schema="tiger",
    )
    op.create_index(
        op.f("secondary_unit_lookup_abbrev_idx"),
        "secondary_unit_lookup",
        ["abbrev"],
        unique=False,
        schema="tiger",
    )
    op.create_table(
        "tabblock",
        sa.Column("gid", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("statefp", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("countyfp", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
        sa.Column("tractce", sa.VARCHAR(length=6), autoincrement=False, nullable=True),
        sa.Column("blockce", sa.VARCHAR(length=4), autoincrement=False, nullable=True),
        sa.Column("tabblock_id", sa.VARCHAR(length=16), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("mtfcc", sa.VARCHAR(length=5), autoincrement=False, nullable=True),
        sa.Column("ur", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("uace", sa.VARCHAR(length=5), autoincrement=False, nullable=True),
        sa.Column("funcstat", sa.VARCHAR(length=1), autoincrement=False, nullable=True),
        sa.Column("aland", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("awater", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("intptlat", sa.VARCHAR(length=11), autoincrement=False, nullable=True),
        sa.Column("intptlon", sa.VARCHAR(length=12), autoincrement=False, nullable=True),
        sa.Column(
            "the_geom",
            geoalchemy2.types.Geometry(
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "geometrytype(the_geom) = 'MULTIPOLYGON'::text OR the_geom IS NULL",
            name=op.f("enforce_geotype_geom"),
        ),
        sa.CheckConstraint("st_ndims(the_geom) = 2", name=op.f("enforce_dims_geom")),
        sa.CheckConstraint("st_srid(the_geom) = 4269", name=op.f("enforce_srid_geom")),
        sa.PrimaryKeyConstraint("tabblock_id", name=op.f("tabblock_pkey")),
        schema="tiger",
    )
    op.create_table(
        "loader_platform",
        sa.Column("os", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("declare_sect", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("pgbin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("wget", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("unzip_command", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("psql", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("path_sep", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("loader", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("environ_set_command", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("county_process_command", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("os", name=op.f("loader_platform_pkey")),
        schema="tiger",
    )
    op.create_table(
        "loader_platform",
        sa.Column("os", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("declare_sect", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("pgbin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("wget", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("unzip_command", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("psql", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("path_sep", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("loader", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("environ_set_command", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("county_process_command", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("os", name=op.f("loader_platform_pkey")),
    )
    op.create_table(
        "direction_lookup",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("abbrev", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("direction_lookup_pkey")),
        schema="tiger",
    )
    op.create_index(
        op.f("direction_lookup_abbrev_idx"),
        "direction_lookup",
        ["abbrev"],
        unique=False,
        schema="tiger",
    )
    op.create_table(
        "countysub_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("county", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cs_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "st_code", "co_code", "cs_code", name=op.f("countysub_lookup_pkey")
        ),
        schema="tiger",
    )
    op.create_index(
        op.f("countysub_lookup_state_idx"),
        "countysub_lookup",
        ["state"],
        unique=False,
        schema="tiger",
    )
    op.create_index(
        op.f("countysub_lookup_name_idx"),
        "countysub_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
        schema="tiger",
    )
    op.create_table(
        "direction_lookup",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("abbrev", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("name", name=op.f("direction_lookup_pkey")),
    )
    op.create_index(
        op.f("direction_lookup_abbrev_idx"), "direction_lookup", ["abbrev"], unique=False
    )
    op.create_table(
        "loader_lookuptables",
        sa.Column(
            "process_order",
            sa.INTEGER(),
            server_default=sa.text("1000"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lookup_name",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="This is the table name to inherit from and suffix of resulting output table -- how the table will be named --  edges here would mean -- ma_edges , pa_edges etc. except in the case of national tables. national level tables have no prefix",
        ),
        sa.Column(
            "table_name",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="suffix of the tables to load e.g.  edges would load all tables like *edges.dbf(shp)  -- so tl_2010_42129_edges.dbf .  ",
        ),
        sa.Column(
            "single_mode",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "load",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
            comment="Whether or not to load the table.  For states and zcta5 (you may just want to download states10, zcta510 nationwide file manually) load your own into a single table that inherits from tiger.states, tiger.zcta5.  You'll get improved performance for some geocoding cases.",
        ),
        sa.Column(
            "level_county",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "level_state",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "level_nation",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
            comment="These are tables that contain all data for the whole US so there is just a single file",
        ),
        sa.Column("post_load_process", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "single_geom_mode",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "insert_mode",
            sa.CHAR(length=1),
            server_default=sa.text("'c'::bpchar"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("pre_load_process", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "columns_exclude",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
            comment="List of columns to exclude as an array. This is excluded from both input table and output table and rest of columns remaining are assumed to be in same order in both tables. gid, geoid,cpi,suffix1ce are excluded if no columns are specified.",
        ),
        sa.Column(
            "website_root_override",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Path to use for wget instead of that specified in year table.  Needed currently for zcta where they release that only for 2000 and 2010",
        ),
        sa.PrimaryKeyConstraint("lookup_name", name=op.f("loader_lookuptables_pkey")),
        schema="tiger",
    )
    op.create_table(
        "loader_lookuptables",
        sa.Column(
            "process_order",
            sa.INTEGER(),
            server_default=sa.text("1000"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "lookup_name",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="This is the table name to inherit from and suffix of resulting output table -- how the table will be named --  edges here would mean -- ma_edges , pa_edges etc. except in the case of national tables. national level tables have no prefix",
        ),
        sa.Column(
            "table_name",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="suffix of the tables to load e.g.  edges would load all tables like *edges.dbf(shp)  -- so tl_2010_42129_edges.dbf .  ",
        ),
        sa.Column(
            "single_mode",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "load",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
            comment="Whether or not to load the table.  For states and zcta5 (you may just want to download states10, zcta510 nationwide file manually) load your own into a single table that inherits from tiger.states, tiger.zcta5.  You'll get improved performance for some geocoding cases.",
        ),
        sa.Column(
            "level_county",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "level_state",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "level_nation",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
            comment="These are tables that contain all data for the whole US so there is just a single file",
        ),
        sa.Column("post_load_process", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "single_geom_mode",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "insert_mode",
            sa.CHAR(length=1),
            server_default=sa.text("'c'::bpchar"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("pre_load_process", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "columns_exclude",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
            comment="List of columns to exclude as an array. This is excluded from both input table and output table and rest of columns remaining are assumed to be in same order in both tables. gid, geoid,cpi,suffix1ce are excluded if no columns are specified.",
        ),
        sa.Column(
            "website_root_override",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Path to use for wget instead of that specified in year table.  Needed currently for zcta where they release that only for 2000 and 2010",
        ),
        sa.PrimaryKeyConstraint("lookup_name", name=op.f("loader_lookuptables_pkey")),
    )
    op.create_table(
        "zip_lookup",
        sa.Column("zip", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("county", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cs_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cousub", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("pl_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("place", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cnt", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("zip", name=op.f("zip_lookup_pkey")),
        schema="tiger",
    )
    op.create_table(
        "street_type_lookup",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("abbrev", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "is_hw",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("street_type_lookup_pkey")),
        schema="tiger",
    )
    op.create_index(
        op.f("street_type_lookup_abbrev_idx"),
        "street_type_lookup",
        ["abbrev"],
        unique=False,
        schema="tiger",
    )
    op.create_table(
        "street_type_lookup",
        sa.Column("name", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("abbrev", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "is_hw",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("street_type_lookup_pkey")),
    )
    op.create_index(
        op.f("street_type_lookup_abbrev_idx"), "street_type_lookup", ["abbrev"], unique=False
    )
    op.create_table(
        "state_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=40), autoincrement=False, nullable=True),
        sa.Column("abbrev", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
        sa.Column("statefp", sa.CHAR(length=2), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("st_code", name=op.f("state_lookup_pkey")),
        sa.UniqueConstraint(
            "abbrev",
            name=op.f("state_lookup_abbrev_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("state_lookup_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "statefp",
            name=op.f("state_lookup_statefp_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        schema="tiger",
    )
    op.create_table(
        "zip_lookup_all",
        sa.Column("zip", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("county", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cs_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cousub", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("pl_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("place", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cnt", sa.INTEGER(), autoincrement=False, nullable=True),
        schema="tiger",
    )
    op.create_table(
        "state_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=40), autoincrement=False, nullable=True),
        sa.Column("abbrev", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
        sa.Column("statefp", sa.CHAR(length=2), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("st_code", name=op.f("state_lookup_pkey")),
        sa.UniqueConstraint(
            "abbrev",
            name=op.f("state_lookup_abbrev_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "name",
            name=op.f("state_lookup_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "statefp",
            name=op.f("state_lookup_statefp_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "zip_lookup_all",
        sa.Column("zip", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("county", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cs_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cousub", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("pl_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("place", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.Column("cnt", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "county_lookup",
        sa.Column("st_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("state", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column("co_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=90), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("st_code", "co_code", name=op.f("county_lookup_pkey")),
        schema="tiger",
    )
    op.create_index(
        op.f("county_lookup_state_idx"), "county_lookup", ["state"], unique=False, schema="tiger"
    )
    op.create_index(
        op.f("county_lookup_name_idx"),
        "county_lookup",
        [sa.literal_column("soundex(name::text)")],
        unique=False,
        schema="tiger",
    )
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_created_at"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_booking_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_bookings_truck_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_org_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_move_date"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_effective_start"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_effective_end"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_customer_email"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_created_at"), table_name="bookings")
    op.drop_index("idx_booking_availability", table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_trucks_status"), table_name="trucks")
    op.drop_index(op.f("ix_trucks_org_id"), table_name="trucks")
    op.drop_index(op.f("ix_trucks_license_plate"), table_name="trucks")
    op.drop_index(op.f("ix_trucks_created_at"), table_name="trucks")
    op.drop_table("trucks")
    op.drop_index(op.f("ix_pricing_configs_org_id"), table_name="pricing_configs")
    op.drop_index(op.f("ix_pricing_configs_is_active"), table_name="pricing_configs")
    op.drop_index(op.f("ix_pricing_configs_created_at"), table_name="pricing_configs")
    op.drop_table("pricing_configs")
    op.drop_index(op.f("ix_insurance_policies_org_id"), table_name="insurance_policies")
    op.drop_index(op.f("ix_insurance_policies_expiry_date"), table_name="insurance_policies")
    op.drop_index(op.f("ix_insurance_policies_created_at"), table_name="insurance_policies")
    op.drop_table("insurance_policies")
    op.drop_index(op.f("ix_drivers_org_id"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_is_verified"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_email"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_drivers_license_number"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_created_at"), table_name="drivers")
    op.drop_table("drivers")
    op.drop_index(op.f("ix_organizations_status"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_email"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_created_at"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_customer_sessions_session_token"), table_name="customer_sessions")
    op.drop_index(op.f("ix_customer_sessions_is_verified"), table_name="customer_sessions")
    op.drop_index(op.f("ix_customer_sessions_identifier"), table_name="customer_sessions")
    op.drop_index(op.f("ix_customer_sessions_expires_at"), table_name="customer_sessions")
    op.drop_index(op.f("ix_customer_sessions_created_at"), table_name="customer_sessions")
    op.drop_table("customer_sessions")
    # ### end Alembic commands ###
