"""add_truck_photos

Revision ID: 842955808270
Revises: 627716ebfd69
Create Date: 2025-11-21 09:54:26.714712+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842955808270'
down_revision: Union[str, None] = '627716ebfd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('photo_front', sa.String(length=512), nullable=True))
    op.add_column('trucks', sa.Column('photo_back', sa.String(length=512), nullable=True))
    op.add_column('trucks', sa.Column('photo_left', sa.String(length=512), nullable=True))
    op.add_column('trucks', sa.Column('photo_right', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'photo_right')
    op.drop_column('trucks', 'photo_left')
    op.drop_column('trucks', 'photo_back')
    op.drop_column('trucks', 'photo_front')
    # ### end Alembic commands ###
